### ISSUE TITLE
Loading Addon

### ISSUE THREAD

**Issue by Dalmine007** [MindFreeze/hassio-axpert#1]
Hi I am having an issue loading the addon, For the repo I am using the following URL
https://github.com/MindFreeze/hassio-axpert

But unfortunately, I am getting the following error in my log files.
`18-12-03 13:31:03 INFO (MainThread) [hassio.addons.git] Clone add-on https://github.com/MindFreeze/hassio-axpert repository
18-12-03 13:31:06 WARNING (MainThread) [hassio.addons.data] Can't read repository information from /data/addons/git/0ebb3a46/repository.json
18-12-03 13:31:06 INFO (MainThread) [hassio.addons] Load add-ons: 48 all - 0 new - 0 remove`

**Comment by manju850** [comment]
did
 you able fix this?

**Comment by MindFreeze** [comment]
Added installation instructions to README
