### ISSUE TITLE
implement Python3

### ISSUE THREAD

**Issue by niesamowitysmyk** [MindFreeze/hassio-axpert#10]
Hi.
I'm trying to implement changes to python3. First, I changed the code in the Dockerfile. I followed your code for "Daly BMS". It works, the solution installs, but I have a problem in the monitor.py code:
"
   try:
         xmodem_crc_func = crcmod.predefined.mkCrcFun(rb'xmodem')
         command_crc = command + unhexlify(hex(xmodem_crc_func(command)).replace('0x','',1)) + '\x0d'
"

I see an error in the add-on log:

"
error parsing inverter data...: cannot access local variable 'file' where it is not associated with a value
QPIRI
error reading inverter...: Unicode-objects must be encoded before calculating a CRC
error parsing inverter data...: cannot access local variable 'file' where it is not associated with a value
QPGS0
error reading inverter...: Unicode-objects must be encoded before calculating a CRC
error parsing inverter data...: cannot access local variable 'file' where it is not associated with a value
QPIGS
error reading inverter...: Unicode-objects must be encoded before calculating a CRC
"

I can't figure out how to solve the problem. I know you no longer support this add-on, but maybe you could find a solution? I have been using this supplement for years and I really like it. This is the only solution that works natively with USB

**Comment by niesamowitysmyk** [comment]
I asked chatGPT for help too:)
I am attaching working corrected files:

1. DockerFile
2. monitor.py
3. requirements.txt
4. run.sh (only python -->python3 line)
5. send_cmd.py (only python -->python3 line)

Solution works now:)

[axpert.zip](https://github.com/MindFreeze/hassio-axpert/files/15204200/axpert.zip)

**Comment by MindFreeze** [comment]
I was just fixing this the other day because it broke. But I just changed the base images and still use python 2.
Haven't uploaded the updates yet.
I'll give you zip a go and switch to python3 if there are no issues

**Comment by MindFreeze** [comment]
I adapted your changes and switched to python 3. Thanks @niesamowitysmyk

**Comment by niesamowitysmyk** [comment]
Thank you very much for your support!
Regards!
