### ISSUE TITLE
Failed to install add-on

### ISSUE THREAD

**Issue by heibertelf** [MindFreeze/hassio-axpert#11]
The command '/bin/ash -o pipefail -c apk add --no-cache python2 git && python2 -m ensurepip && rm -r /usr/lib/python*/ensurepip && git clone https://github.com/aquarat/mpp-solar.git . && pip install --upgrade paho-mqtt && python ./setup.py install' returned a non-zero code: 1

![image](https://github.com/MindFreeze/hassio-axpert/assets/80182970/91e98afd-0bef-4bce-8243-81ea7fa08b92)

**Comment by MindFreeze** [comment]
I think you're using some fork. I don't use mpp-solar or python 2 here

**Comment by MindFreeze** [comment]
Ah wait. You're trying Axpert Command and that is in another repo that hasn't been maintained

**Comment by heibertelf** [comment]
> You're trying Axpert Command

Yes. I have Sila invertor, it could be compatible, but when i try Axpect monitor addon, it says 
```
/dev/hidraw0
QPGS0
error reading inverter...: NAKss
/dev/hidraw0
```
In another thread i read that Command can help.
My invertor connected directly to haos server via usb port (without rs232 converter, it have own onboard usb port), can this be a problem?

**Comment by MindFreeze** [comment]
It's possible the device is not hidraw0 if you have other usb devices.
Or it might just not be compatible
