### ISSUE TITLE
Docker RESTARTING (139)

### ISSUE THREAD

**Issue by Mieliebom** [MindFreeze/hassio-axpert#2]
Hi. Thank you for this very interesting piece of work you did!

I have followed all instructions but I didnt see any messages coming through. Upon further investigation I did a docker ps. It seems that the docker ha-voltronic-mqtt keeps sitting in a RESTARTING (139) state.

I have searched the internet for this and most comments recommended that there could be an architecture issue. I’m running a Pi Zero W so it shouldn’t be an issue. Anyway, I uncommented the part to rebuild in docker-compose.yml to see if this will work. I’ve tried to stop all dockers, doing a docker prune, then starting/rebuilding but still the error persists.

**Comment by jaakkom** [comment]
My device is showing in TTYACM0, not hidraw. Causes docker crashing on error open file `descriptor: [Errno 1] Operation not permitted: '/dev/serial/by-id/usb-04e2_1410-if00'`

Wondering if it is the same problem? 

Config.json lists only "/dev/hidraw0" as possible device

**Comment by jaakkom** [comment]
Made fork that allows /dev/ttyACM0 and /dev/ttyACM1 to be used, now it fails on "Read operation timeout" @MindFreeze Any ideas what to check next?

**Comment by MindFreeze** [comment]
@jaakkom I looked at the fork. The only thing that comes to mind is that you may have forgotten to set the device to /dev/ttyACM0 or whatever in the options after install. You could also get this error occasionally even though it is working but if nothing is published, there is definately a problem.
There used to be a problem that if a device listed in config.json wasn't present at start, it would error out but that was a different error and I don't know if it is still a problem.

P.S. I don't remember seeing this issue from 2020. Don't know how I missed it

**Comment by jaakkom** [comment]
Ok. I think i figured out my problem. Its not working with usb-usb cable. The inverter i have is Easun ISolar SMG II 3kw 24V. 

Tried to listen usb device with my computer, and it didnt give any data.

Orderd usb to console cable to try if it works with it, will update if works with it.
