### ISSUE TITLE
Update commands for inverter not working

### ISSUE THREAD

**Issue by hpema** [MindFreeze/hassio-axpert#3]
Hi...

Thanks for this project, helped me get started with reading data from Axpert inverter.

What im struggling with is sending commands for updating the inverter. Is there a different format on how to send the commands.

This does not work:

response = serial_command('POP02')

response is NAK.

Guidance on how to get this working will be greatly appreciated.

Kind regards
Hemant

**Comment by MindFreeze** [comment]
I know this is an old issue but my notifications were off. 

I actually have another addon for sending commands https://github.com/MindFreeze/axpert_cmd
