### ISSUE TITLE
No idea how to install.

### ISSUE THREAD

**Issue by KristianHeider** [MindFreeze/hassio-axpert#4]
Do I run this container on hassio portainer. I need some more imput. Can someone give me a link?

**Comment by KristianHeider** [comment]
21-04-20 13:23:45 INFO (MainThread) [supervisor.store.git] Cloning add-on https://github.com/mindfreeze/hassio-axpert repository
21-04-20 13:23:47 ERROR (MainThread) [supervisor.store] https://github.com/mindfreeze/hassio-axpert is not a valid add-on repository
21-04-20 13:23:47 INFO (MainThread) [supervisor.resolution.module] Create new issue IssueType.CORRUPT_REPOSITORY - ContextType.STORE / 0ebb3a46
21-04-20 13:23:47 INFO (MainThread) [supervisor.resolution.module] Create new suggestion SuggestionType.EXECUTE_REMOVE - ContextType.STORE / 0ebb3a46
21-04-20 13:23:47 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'startup' with 'before' is deprecated. Please report this to the maintainer of Coffee Maker
21-04-20 13:23:47 WARNING (MainThread) [supervisor.store.data] No repository information exists at /data/addons/git/0ebb3a46

**Comment by KristianHeider** [comment]
Ok, after install local AddOn it will still not work.
I've got an eaSun Hybrid Solar Inverter 5kW and the given answer is invalid

I used your code and get no correct answer.

~~Now I installed eaSun WatchPower to listen correct format and copy same command to Addon:~~
~~crc 0x51 0x50 0x49 0x3f 0x3f 0xd(QPI)~~

~~This is, what I receive:~~
~~##1 0x5e 0x30 0x1b 0xe3 0xd 0x0 0x0 0x0(^0�~~
~~)~~
~~There is no '(' at begining. Debug line displays only string in ()~~

Was wrong by working with strings. With bytes I cross checked your crc calculation with eaSun WatchPower is correct. Only  my inverter just answer wrong on USB (hidraw0) direct connection. 
My last try is to use "ttyUSB0" with RS232 converter.

**Comment by KristianHeider** [comment]
Even eaSun WatchPower does not work on my Mac with RS232:
2021-04-22 Serial-QPI.log:
[2021-04-22 10:49:44]^0
[2021-04-22 10:49:44]^0
[2021-04-22 10:49:44]^0
[2021-04-22 10:49:44]^0
[2021-04-22 10:49:45]^0

On the other hand: WLAN-RS232 dongle works and sends data to internet...

**Comment by KristianHeider** [comment]
![image](https://user-images.githubusercontent.com/17590490/115715443-6c1a5480-a378-11eb-94f6-c6d8c97df376.png)
I guess, my invert use a different protocol.

**Comment by MindFreeze** [comment]
This addon is a bit low level and may not work on different firmware versions. My inverters don't even conform to the official protocol :/
