### ISSUE TITLE
I have and Error in logs.

### ISSUE THREAD

**Issue by drageeblue** [MindFreeze/hassio-axpert#6]
I have Voltronic Axpert III 3kw inverter and installed on hassio hassio-axpert application. When it start that has an error. IT can't receive any data from inverter, Mqtt queue is empty.

Is it support my inverter this application? 

By the way I can receive data from my inverter via https://github.com/ned-kelly/docker-voltronic-homeassistant docker application on an additional raspberry pi device to the mqtt.

LOGS:
Axpert Inverter
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
/dev/hidraw0
QID
(553555355535552�
Reading from inverter 55355535553555
QPGS0
error reading inverter...: NAKss
/dev/hidraw0
QPGS0
error reading inverter...: NAKss
/dev/hidraw0
QPGS0
error reading inverter...: NAKss
/dev/hidraw0
QPGS0
error reading inverter...: NAKss
/dev/hidraw0
.....

**Comment by MindFreeze** [comment]
You might have incompatible firmware. If the other thing works, just use it.

**Comment by drageeblue** [comment]
I want to use only one raspberry pi device for hassio and receive data from the inverter to reduce electricity consumption in my RV. I have version 41.15.  Do you know which version I can use?

Product link: https://voltronicpower.com/en-US/Product/Detail/Axpert-VM-III-1.5KVA-3KVA-5KVA

**Comment by MindFreeze** [comment]
You can try to convert the other project to a HA addon. 
Or try running it with the Portainer addon. I haven't used it but others run all sorts of docker containers with it.
