### ISSUE TITLE
s6-overlay-suexec: fatal: can only run as pid 1

### ISSUE THREAD

**Issue by niesamowitysmyk** [MindFreeze/hassio-axpert#7]
H.
this solution looks perfect, but i get a startup error:
s6-overlay-suexec: fatal: can only run as pid 1

My config:
Raspberry Pi 4B
core-2022.5.5
supervisor-2022.05.2
Home Assistant OS 7.6
Please Help:)

**Comment by MindFreeze** [comment]
I have no idea what this error is. 
Have you installed it as a HA addon or just running it through docker?

**Comment by niesamowitysmyk** [comment]
Hi, Thanks for reply.
Installed via HASSIO addon. Today i installed OS version 8.1 - the same message: s6-overlay-suexec: fatal: can only run as pid 1
Log:
22-05-27 13:53:50 INFO (SyncWorker_1) [supervisor.docker.interface] Cleaning addon_07ba83e9_axpert application
22-05-27 13:53:51 INFO (SyncWorker_1) [supervisor.docker.addon] Starting Docker add-on 07ba83e9/aarch64-addon-axpert with version 0.4.4
22-05-27 13:53:52 ERROR (SyncWorker_4) [supervisor.docker.interface] Container addon_07ba83e9_axpert is not running
22-05-27 13:53:52 ERROR (SyncWorker_2) [supervisor.docker.interface] Container addon_07ba83e9_axpert is not running

**Comment by niesamowitysmyk** [comment]
I found similar problem:
https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/issues/335
Maybe adding an option "init: false" to the config.json will solve the problem?

**Comment by MindFreeze** [comment]
You can try this yourself with samba, ssh or any other addon that gives you access to HA files. Put the contents of this repo in addons/axpert, change the config and you will see "Local add-ons" in the addon store. Might need to click "Check for updates" in the top-right menu.

I don't have this error and can't test it for you.

**Comment by niesamowitysmyk** [comment]
Hi, 
Thanks for thanks for the answer and tips.
I have added the following entry in config.json:
....
    "schema": {
        "mqtt_server": "str",
        "mqtt_user": "str",
        "mqtt_pass": "str",
        "mqtt_client_id": "str",
        "mqtt_topic_parallel": "str",
        "mqtt_topic_settings": "str",
        "mqtt_topic": "str",
	"device": "str"
    },
    "init": false
}

The add-on has started now but has stopped

I found similar problem:
https://community.home-assistant.io/t/addons-not-starting-in-hass-io/44419

Maybe you should add this option in the official add-on?

My log:
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
/run/s6/basedir/scripts/rc.init: line 40: /run.sh: not found
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by MindFreeze** [comment]
it says run.sh is missing, which makes no sense. You may have a corrupted file system. Happened to me a few times, especially when using SD cards. I suggest trying a fresh install on different storage.

**Comment by niesamowitysmyk** [comment]
It works perfectly :)
The previous problem was in converting coding files while copying to local storage. 
I strongly recommend adding the init: false in config.json option in the next version this addon.
Regards!!!

**Comment by MindFreeze** [comment]
@niesamowitysmyk just added init:false to a new version
