### ISSUE TITLE
Description of Nakss

### ISSUE THREAD

**Issue by tranquilbigfoot** [MindFreeze/hassio-axpert#8]
Hi! Thanks for developing this addon for Home Assistant.

When trying to integrate my Axpert inverter over USB, I'm getting the following error:
```
error reading inverter...: NAKss
/dev/hidraw0
```
I have verified that it's at /dev/hidraw0 and I'm not sure where to take it from here.

Thanks.

**Comment by MindFreeze** [comment]
There are some issues with this addon and these inverters in general. Nakss means the inverter didn't respond or it  couldn't even understand the request.

First, this addon's communication is not optimal. I have another addon called axpert-command that uses a more stable method for communication but its purpose is to send commands without waiting for a response.

Second these inverters have a bunch of different firmware versions and some are incompatible with others. Your inverter may not understand the command or its response may be in a different format.

I randomly get NAKss from my inverters but most of the responses are fine so I can ignore that but if you only get NAKss then maybe the protocol is just incompatible.

I am sorry but I can't provide more info than that.

**Comment by tranquilbigfoot** [comment]
Awesome — thank you for letting me know what the error means. I'll try axpert-command instead 😎
